<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from funding/xml/schema/CRM/Funding/FundingClearingResourcesItem.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:c03dc30993c5f4e93e2229a91c766a2c)
 */
use CRM_Funding_ExtensionUtil as E;

/**
 * Database access object for the ClearingResourcesItem entity.
 */
class CRM_Funding_DAO_ClearingResourcesItem extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_funding_clearing_resources_item';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique FundingClearingResourcesItem ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to FundingClearingProcess
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $clearing_process_id;

  /**
   * FK to FundingApplicationResourcesItem
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $app_resources_item_id;

  /**
   * @var string
   *   (SQL type: varchar(64))
   *   Note that values will be retrieved from the database as a string.
   */
  public $status;

  /**
   * FK to File
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $file_id;

  /**
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $receipt_number;

  /**
   * @var string
   *   (SQL type: date)
   *   Note that values will be retrieved from the database as a string.
   */
  public $payment_date;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $recipient;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $reason;

  /**
   * @var string
   *   (SQL type: decimal(10,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $amount;

  /**
   * @var string|null
   *   (SQL type: decimal(10,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $amount_admitted;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_funding_clearing_resources_item';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Clearing Resources Items') : E::ts('Clearing Resources Item');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique FundingClearingResourcesItem ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_clearing_resources_item.id',
          'table_name' => 'civicrm_funding_clearing_resources_item',
          'entity' => 'ClearingResourcesItem',
          'bao' => 'CRM_Funding_DAO_ClearingResourcesItem',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'clearing_process_id' => [
          'name' => 'clearing_process_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Clearing Process ID'),
          'description' => E::ts('FK to FundingClearingProcess'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_clearing_resources_item.clearing_process_id',
          'table_name' => 'civicrm_funding_clearing_resources_item',
          'entity' => 'ClearingResourcesItem',
          'bao' => 'CRM_Funding_DAO_ClearingResourcesItem',
          'localizable' => 0,
          'FKClassName' => 'CRM_Funding_DAO_ClearingProcess',
          'html' => [
            'type' => 'EntityRef',
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_funding_clearing_process',
            'keyColumn' => 'id',
            'labelColumn' => 'id',
            'prefetch' => 'false',
          ],
          'add' => NULL,
        ],
        'app_resources_item_id' => [
          'name' => 'app_resources_item_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('App Resources Item ID'),
          'description' => E::ts('FK to FundingApplicationResourcesItem'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_clearing_resources_item.app_resources_item_id',
          'table_name' => 'civicrm_funding_clearing_resources_item',
          'entity' => 'ClearingResourcesItem',
          'bao' => 'CRM_Funding_DAO_ClearingResourcesItem',
          'localizable' => 0,
          'FKClassName' => 'CRM_Funding_DAO_ApplicationResourcesItem',
          'html' => [
            'type' => 'EntityRef',
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_funding_app_resources_item',
            'keyColumn' => 'id',
            'labelColumn' => 'identifier',
            'prefetch' => 'false',
          ],
          'add' => NULL,
        ],
        'status' => [
          'name' => 'status',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Status'),
          'required' => TRUE,
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_clearing_resources_item.status',
          'table_name' => 'civicrm_funding_clearing_resources_item',
          'entity' => 'ClearingResourcesItem',
          'bao' => 'CRM_Funding_DAO_ClearingResourcesItem',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'callback' => 'Civi\Funding\FundingPseudoConstants::getClearingItemStatus',
          ],
          'add' => NULL,
        ],
        'file_id' => [
          'name' => 'file_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('File ID'),
          'description' => E::ts('FK to File'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_clearing_resources_item.file_id',
          'table_name' => 'civicrm_funding_clearing_resources_item',
          'entity' => 'ClearingResourcesItem',
          'bao' => 'CRM_Funding_DAO_ClearingResourcesItem',
          'localizable' => 0,
          'FKClassName' => 'CRM_Core_DAO_File',
          'html' => [
            'type' => 'EntityRef',
          ],
          'add' => NULL,
        ],
        'receipt_number' => [
          'name' => 'receipt_number',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Receipt Number'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_clearing_resources_item.receipt_number',
          'table_name' => 'civicrm_funding_clearing_resources_item',
          'entity' => 'ClearingResourcesItem',
          'bao' => 'CRM_Funding_DAO_ClearingResourcesItem',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'payment_date' => [
          'name' => 'payment_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => E::ts('Payment Date'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_clearing_resources_item.payment_date',
          'table_name' => 'civicrm_funding_clearing_resources_item',
          'entity' => 'ClearingResourcesItem',
          'bao' => 'CRM_Funding_DAO_ClearingResourcesItem',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDate',
          ],
          'add' => NULL,
        ],
        'recipient' => [
          'name' => 'recipient',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Recipient'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_clearing_resources_item.recipient',
          'table_name' => 'civicrm_funding_clearing_resources_item',
          'entity' => 'ClearingResourcesItem',
          'bao' => 'CRM_Funding_DAO_ClearingResourcesItem',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'reason' => [
          'name' => 'reason',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Reason'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_clearing_resources_item.reason',
          'table_name' => 'civicrm_funding_clearing_resources_item',
          'entity' => 'ClearingResourcesItem',
          'bao' => 'CRM_Funding_DAO_ClearingResourcesItem',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'amount' => [
          'name' => 'amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Amount'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_clearing_resources_item.amount',
          'dataPattern' => '/^\d{1,10}(\.\d{2})?$/',
          'table_name' => 'civicrm_funding_clearing_resources_item',
          'entity' => 'ClearingResourcesItem',
          'bao' => 'CRM_Funding_DAO_ClearingResourcesItem',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'amount_admitted' => [
          'name' => 'amount_admitted',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Amount Admitted'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_clearing_resources_item.amount_admitted',
          'dataPattern' => '/^\d{1,10}(\.\d{2})?$/',
          'table_name' => 'civicrm_funding_clearing_resources_item',
          'entity' => 'ClearingResourcesItem',
          'bao' => 'CRM_Funding_DAO_ClearingResourcesItem',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'funding_clearing_resources_item', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'funding_clearing_resources_item', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
