<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from funding/xml/schema/CRM/Funding/FundingFormStringTranslation.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:15a44538a5df6501f3805712c8c9afdf)
 */
use CRM_Funding_ExtensionUtil as E;

/**
 * Database access object for the FundingFormStringTranslation entity.
 */
class CRM_Funding_DAO_FundingFormStringTranslation extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_funding_form_string_translation';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Paths for accessing this entity in the UI.
   *
   * @var string[]
   */
  protected static $_paths = [
    'update' => 'civicrm/funding/funding/form-string-translation/edit#?FundingFormStringTranslation1=[id]',
  ];

  /**
   * Unique FundingFormStringTranslation ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to FundingProgram
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $funding_program_id;

  /**
   * FK to FundingCaseType
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $funding_case_type_id;

  /**
   * Original
   *
   * @var string
   *   (SQL type: varchar(8000) COLLATE utf8mb4_bin)
   *   Note that values will be retrieved from the database as a string.
   */
  public $msg_text;

  /**
   * Translation
   *
   * @var string
   *   (SQL type: varchar(8000) COLLATE utf8mb4_bin NOT)
   *   Note that values will be retrieved from the database as a string.
   */
  public $new_text;

  /**
   * @var string
   *   (SQL type: timestamp ON UPDATE CURRENT_TIMESTAMP)
   *   Note that values will be retrieved from the database as a string.
   */
  public $modification_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_funding_form_string_translation';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Funding Form String Translations') : E::ts('Funding Form String Translation');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique FundingFormStringTranslation ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_form_string_translation.id',
          'table_name' => 'civicrm_funding_form_string_translation',
          'entity' => 'FundingFormStringTranslation',
          'bao' => 'CRM_Funding_DAO_FundingFormStringTranslation',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'funding_program_id' => [
          'name' => 'funding_program_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Funding Program'),
          'description' => E::ts('FK to FundingProgram'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_form_string_translation.funding_program_id',
          'table_name' => 'civicrm_funding_form_string_translation',
          'entity' => 'FundingFormStringTranslation',
          'bao' => 'CRM_Funding_DAO_FundingFormStringTranslation',
          'localizable' => 0,
          'FKClassName' => 'CRM_Funding_DAO_FundingProgram',
          'html' => [
            'type' => 'EntityRef',
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_funding_program',
            'keyColumn' => 'id',
            'labelColumn' => 'title',
            'prefetch' => 'false',
          ],
          'add' => NULL,
        ],
        'funding_case_type_id' => [
          'name' => 'funding_case_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Funding Case Type'),
          'description' => E::ts('FK to FundingCaseType'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_form_string_translation.funding_case_type_id',
          'table_name' => 'civicrm_funding_form_string_translation',
          'entity' => 'FundingFormStringTranslation',
          'bao' => 'CRM_Funding_DAO_FundingFormStringTranslation',
          'localizable' => 0,
          'FKClassName' => 'CRM_Funding_DAO_FundingCaseType',
          'html' => [
            'type' => 'EntityRef',
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_funding_case_type',
            'keyColumn' => 'id',
            'labelColumn' => 'title',
            'prefetch' => 'false',
          ],
          'add' => NULL,
        ],
        'msg_text' => [
          'name' => 'msg_text',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Original'),
          'description' => E::ts('Original'),
          'required' => TRUE,
          'maxlength' => 8000,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_form_string_translation.msg_text',
          'table_name' => 'civicrm_funding_form_string_translation',
          'entity' => 'FundingFormStringTranslation',
          'bao' => 'CRM_Funding_DAO_FundingFormStringTranslation',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
        'new_text' => [
          'name' => 'new_text',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Translation'),
          'description' => E::ts('Translation'),
          'required' => FALSE,
          'maxlength' => 8000,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_form_string_translation.new_text',
          'table_name' => 'civicrm_funding_form_string_translation',
          'entity' => 'FundingFormStringTranslation',
          'bao' => 'CRM_Funding_DAO_FundingFormStringTranslation',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
        'modification_date' => [
          'name' => 'modification_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Modification Date'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_form_string_translation.modification_date',
          'table_name' => 'civicrm_funding_form_string_translation',
          'entity' => 'FundingFormStringTranslation',
          'bao' => 'CRM_Funding_DAO_FundingFormStringTranslation',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'funding_form_string_translation', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'funding_form_string_translation', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_translation' => [
        'name' => 'UI_translation',
        'field' => [
          0 => 'funding_program_id',
          1 => 'funding_case_type_id',
          2 => 'msg_text',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_funding_form_string_translation::1::funding_program_id::funding_case_type_id::msg_text',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
