<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from funding/xml/schema/CRM/Funding/FundingCasePermissionsCache.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:60f42b05f805d9d6359f2fce03651700)
 */
use CRM_Funding_ExtensionUtil as E;

/**
 * Database access object for the FundingCasePermissionsCache entity.
 */
class CRM_Funding_DAO_FundingCasePermissionsCache extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_funding_case_permissions_cache';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique FundingCasePermissionsCache ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to FundingCase
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $funding_case_id;

  /**
   * No FK to contact to work with 0 (contact ID on CLI), too
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * Indicates whether the permissions are for internal or remote requests
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_remote;

  /**
   * Permissions as JSON array. If NULL they have to be determined.
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $permissions;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_funding_case_permissions_cache';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Funding Case Permissions Caches') : E::ts('Funding Case Permissions Cache');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'funding_case_id', 'civicrm_funding_case', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique FundingCasePermissionsCache ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_case_permissions_cache.id',
          'table_name' => 'civicrm_funding_case_permissions_cache',
          'entity' => 'FundingCasePermissionsCache',
          'bao' => 'CRM_Funding_DAO_FundingCasePermissionsCache',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'funding_case_id' => [
          'name' => 'funding_case_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Funding Case ID'),
          'description' => E::ts('FK to FundingCase'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_case_permissions_cache.funding_case_id',
          'table_name' => 'civicrm_funding_case_permissions_cache',
          'entity' => 'FundingCasePermissionsCache',
          'bao' => 'CRM_Funding_DAO_FundingCasePermissionsCache',
          'localizable' => 0,
          'FKClassName' => 'CRM_Funding_DAO_FundingCase',
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('No FK to contact to work with 0 (contact ID on CLI), too'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_case_permissions_cache.contact_id',
          'table_name' => 'civicrm_funding_case_permissions_cache',
          'entity' => 'FundingCasePermissionsCache',
          'bao' => 'CRM_Funding_DAO_FundingCasePermissionsCache',
          'localizable' => 0,
          'add' => NULL,
        ],
        'is_remote' => [
          'name' => 'is_remote',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Remote'),
          'description' => E::ts('Indicates whether the permissions are for internal or remote requests'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_case_permissions_cache.is_remote',
          'table_name' => 'civicrm_funding_case_permissions_cache',
          'entity' => 'FundingCasePermissionsCache',
          'bao' => 'CRM_Funding_DAO_FundingCasePermissionsCache',
          'localizable' => 0,
          'add' => NULL,
        ],
        'permissions' => [
          'name' => 'permissions',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Permissions'),
          'description' => E::ts('Permissions as JSON array. If NULL they have to be determined.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_funding_case_permissions_cache.permissions',
          'table_name' => 'civicrm_funding_case_permissions_cache',
          'entity' => 'FundingCasePermissionsCache',
          'bao' => 'CRM_Funding_DAO_FundingCasePermissionsCache',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'funding_case_permissions_cache', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'funding_case_permissions_cache', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_funding_case_id_contact_id_is_remote' => [
        'name' => 'UI_funding_case_id_contact_id_is_remote',
        'field' => [
          0 => 'funding_case_id',
          1 => 'contact_id',
          2 => 'is_remote',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_funding_case_permissions_cache::1::funding_case_id::contact_id::is_remote',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
